name: DT-flood

channels:
  - conda-forge
  - numba

dependencies:
  - pip
  - pip:
    - jupyter
    - git+https://github.com/Deltares-research/FloodAdapt.git
    - gwwapi
    - cwltool
  - cartopy
  - cwltool
  - ipykernel
  - geopandas
  - hydromt_wflow
  - python<3.12

