name: DT-flood

channels:
  - conda-forge
  - numba

dependencies:
  - cartopy
  - ipykernel
  - geopandas
  - hydromt_wflow=0.3
  - python=3.10
  - pip
  - pip:
    - jupyter
    - git+https://github.com/Deltares-research/FloodAdapt.git
    - gwwapi