script_update_wflow:  # type 'File'
    class: File
    path: a/file/path
script_update_sfincs:  # type 'File'
    class: File
    path: a/file/path
script_update_fiat:  # type 'File'
    class: File
    path: a/file/path
script_run_fiat:  # type 'File'
    class: File
    path: a/file/path
script_init:  # type 'File'
    class: File
    path: a/file/path
script_arrange:  # type 'File'
    class: File
    path: a/file/path
scenario: a_string  # type 'string'
fa_database:  # type 'Directory'
    class: Directory
    path: a/directory/path
