oscar_script:
  class: File
  path: oscar_all/oscar.py
endpoint: 
user: 
password: 
service: wflow
filename:
  class: File
  path: wflow_input.tar
oscar_service:
  class: Directory
  path: services

output:
  class: Directory
  path: output