file:
  class: File
  path: wflow_input.tar


# minioEndpoint: minio.sleepy-lumiere4.im.grycap.net
# minioAccesskey: minio
# minioSecretkey: minio123

minioEndpoint: minio.charming-zhukovsky8.im.grycap.net
minioAccesskey: minio
minioSecretkey:

bucketInput: wflow/in
bucketOutput: wflow/out


uploadScript:
  class: File
  path: upload/upload.py

waitScript:
  class: File
  path: wait_output/wait.py