file:
  class: Directory
  path: archive/


minioEndpoint: 
minioAccesskey: 
minioSecretkey: 

bucketInput: wflow/in
bucketOutput: wflow/out


uploadScript:
  class: File
  path: upload/upload.py

waitScript:
  class: File
  path: wait_output/wait.py