oscarScript:
  class: File
  path: oscar_all/oscar.py
endpoint: 
user: 
password: 
service: wflow
filename:
  class: File
  path: wflow_input.tar
oscarService:
  class: Directory
  path: services

fa_database_out:
  class: Directory
  path: output